config/routes.rb
Blog::Application.routes.draw do
  devise_for :users
  get "welcome/index"
  resources :posts do
    resources :comments
  end
  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true, length: {minimum: 5}
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:commenter, :body))
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
		@last = Post.last(5)
	end

	def new
		@post = Post.new
	end

	def create
		#render text: params[:post].inspect
		@post = Post.new(post_params)
		@last = Post.last(5)
		if @post.save
			redirect_to @post
		else 
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
		@last = Post.last(5)
	end

	def edit
		@post = Post.find(params[:id])
		@last = Post.last(5)
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :text))
			redirect_to @post
		else
			render 'edit'
		end
		@last = Post.last(5)
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
		
	end

	private
		def post_params
			params.require(:post).permit(:title, :text)
		end

	before_filter :authenticate_user!

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@last = Post.last(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    
    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Blog", welcome_index_path, :class=>"navbar-brand"%>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Todos los Post", posts_path  %></li>
            <li><%= link_to "Nuevo Post", new_post_path  %></li>
           </ul>
           <ul class="nav navbar-nav navbar-right">
     	      <li class="dropdown navbar-right">
				      <a class="dropdown-toggle" data-toggle="dropdown" href="#">Welcome <%= current_user.email %></a>

			     </li>
          </ul>
        </div>
      </div>
    </div>




            

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Últimos Posts</h3>
            <% if @last%>
              <ul class="nav nav-list">
                <% @last.each do |p| %>
                  <li class="nav-header"><%= link_to p.title, post_path(p) %></li>
                <% end %>
              
            <% else %>
            <ul class="nav nav-list">
               <li class="nav-header">No hay post para mostrar...</li> 
            <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post,  :html => {:class => "form-horizontal"} do |f| %>
	<% if @post.errors.any? %>
		<div id="errorExplanation">
			<h2><%= pluralize(@post.errors.count, "error")%> prohibited this post</h2>
			<ul>
			<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<br />
	<br />
	<div class="form-group">
		<%= f.label :title, :class => "col-sm-2 control-label" %>
		<div class="col-sm-10">
		   <%= f.text_field :title, :class => "form-control" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :text, :class => "col-sm-2 control-label" %>
		<div class="col-sm-10">
		  <%= f.text_field :text, :class => "form-control" %>
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<%= f.submit :class => "btn btn-default btn-lg" %>
		</div>
	</div>

<% end %>

app/views/posts/edit.html.erb
<h1>Editar post</h1>

<%= render 'form' %>

<span class="glyphicon glyphicon-circle-arrow-left"><%= link_to "Back", posts_path %></span>

app/views/posts/index.html.erb
<h1>Mis Post</h1>
<table class="table table-hover">
	<tr>
		<th>Titulo</th>
		<th>Texto</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>
	<% @posts.each do |post| %>
		<tr>
			<td> <%= post.title %> </td>
			<td> <%= post.text %> </td>
			<td> <%= link_to 'Show', post_path(post)%> </td>
			<td> <%= link_to 'Edit', edit_post_path(post)%> </td>
			<td> <%= link_to 'Delete', post_path(post), method: :delete, data: {confirm: 'Está seguro?'}%> </td>
		</tr>
	<% end %>
</table>

<%= link_to "Nuevo Post", new_post_path, :class=>"btn btn-default btn-lg"%>

app/views/posts/new.html.erb
<h1>Nuevo post</h1>

<%= render 'form' %>

<%= link_to "Back", posts_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>


<h3><%= @post.text %></h3>
	


<%= link_to 'Back', posts_path %>
<%= link_to 'edit', edit_post_path(@post)%>

<br /><br />
<legend>Comentarios</legend>
<% @post.comments.each do |comment| %>
	<p>
		<strong><%= comment.commenter %>: </strong><%= comment.body %>
	</p>
	
	<p>
		<%= link_to 'Destroy Comment', [comment.post, comment], method: :delete, data: {confirm: 'Estas seguro?'}%>
	</p>	

<% end %>

<legend>Agregar un comentario</legend>
<%= form_for ([@post, @post.comments.build]) do |f| %>
	<p>
		<%= f.label :commenter %> <br />
		<%= f.text_field :commenter %>
	</p>

	<p>
		<%= f.label :body %> <br />
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit :class => "btn btn-default btn-lg" %>
	</p>

<% end %>

app/views/welcome/index.html.erb
<h1><%= link_to "Bienvenidos a mi sitio web", controller: "posts" %></h1>

<img src="/images/rails.png" alt="rss feed" />